id: A0889DD44
title: Prayer for the Long Life of Dzogchen Rinpoche
type: translation
pechas:
- I8949FF52
- I6A9A34A6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:14.123027
  last_modified_at: 2023-01-04 11:48:14.123032
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8949FF52/D22E: CA1F
  I6A9A34A6/6474: CA1F
